import re
import html
import html2text # 👈 New Import

# Paste your full data here
raw_text = """<your full data>"""

# ... (Your existing HTML generation code goes here) ...

# The final HTML content generated by your existing code:
# html_content = "<html><body>\n" + "\n".join(html_blocks) + "\n</body></html>"

# ⬇️ NEW SECTION: Convert HTML to Markdown ⬇️
## HTML to Markdown Conversion

# 1. Initialize the converter
h = html2text.HTML2Text()
# Optional: Configure the converter for cleaner output
h.body_width = 0 # Prevents line wrapping
h.ignore_links = False
h.ignore_images = True
h.protect_all_italics = True # Prevents single underscores in text from becoming emphasis

# 2. Perform the conversion
markdown_content = h.handle(html_content)

# 3. Save the Markdown output
with open("output_converted_markdown.md", "w", encoding="utf-8") as f:
    f.write(markdown_content)

print("✅ Clean and formatted HTML created: output_formatted_clean.html (font sizes +4px)")
print("✅ Converted Markdown created: output_converted_markdown.md")




# Original line in your script:
# html_segment_texts.append(f'<span style="{style_attr}">{html.escape(text)}</span>')

# 💡 Modified line to preserve Bold/Italics with semantic tags:
escaped_text = html.escape(text)
if "Bold" in style and "Italic" in style:
    # Use <strong> and <em> for bold and italics
    segment = f'<strong><em>{escaped_text}</em></strong>'
elif "Bold" in style:
    # Use <strong> for bold
    segment = f'<strong>{escaped_text}</strong>'
elif "Italic" in style:
    # Use <em> for italics
    segment = f'<em>{escaped_text}</em>'
else:
    # Plain text, wrapped in a span (optional, but good for consistency)
    segment = f'<span>{escaped_text}</span>'

# html2text will convert <strong> to **Markdown** and <em> to *Markdown*
html_segment_texts.append(segment)
