SELECT 
    it.PARENT_CODE,
    it.CHILD_CODE,
    COALESCE(ut.CHILD_DESC, it.CHILD_DESC) AS CHILD_DESC
FROM 
    InternalTable it
LEFT JOIN 
    UnifiedTable ut
ON 
    it.PARENT_CODE = ut.PARENT_CODE
    AND it.CHILD_CODE = ut.CHILD_CODE;
