SELECT 
    ACCESS_OBJECT,
    MAX(CASE WHEN SYSTEM_CODE = 'VU1' THEN concat_ws(';', collect_set(EMAIL)) ELSE NULL END) AS VU1_EMAILS,
    MAX(CASE WHEN SYSTEM_CODE = 'VW3' THEN concat_ws(';', collect_set(EMAIL)) ELSE NULL END) AS VW3_EMAILS
FROM your_table_name
GROUP BY ACCESS_OBJECT;
