SELECT 
    LEVEL1,
    LEVEL2,
    LEVEL3,
    CONCAT_WS(';', COLLECT_SET(DISTINCT SPLIT(VU1_EMAIL, ';'))) AS VU1_EMAIL,
    CONCAT_WS(';', COLLECT_SET(DISTINCT SPLIT(VW3_EMAIL, ';'))) AS VW3_EMAIL
FROM your_table_name
GROUP BY LEVEL1, LEVEL2, LEVEL3;
